python --version
sudo yum -y update
sudo yum install epel-release
sudo yum install ansible
ansible --version
sudo yum install ansible
# sudo amazon-linux-extras install ansible2
sudo amazon-linux-extras install ansible2
ansible --version
mkdir ansible-playbooks
mkdir ansible_playbooks
pwd
ls
cd ~
ls
mkdir ansible-playbooks
ls
nano playbook1.yml
mve playbook1.yml ansible-playbooks
cp playbook1.yml ansible-playbooks
cd ansible-playbooks/
ls
cd playbook1.yml
nano playbook1.yml 
ansible-playbook -i hosts
ansible-playbook -i hosts_linx plybooks/nginx_install_centos.yml
ansible-playbook -i hosts_linx ansible-plybooks/playbook1.yml
pwd
ansible-playbook -i hosts_linx 
pwd
ansible-playbook -i hosts_linx /home/ansible/ansible-playbooks
ansible-playbook -i hosts_linx /home/ansible/ansible-playbooks/playbook1.yml
nano playbook1.yml
ansible-playbook -i hosts_linx /home/ansible/ansible-playbooks/playbook1.yml
nano playbook1.yml
ansible-playbook -i hosts_linx /home/ansible/ansible-playbooks/playbook1.yml
ls
cd ..
ls
cd /
ls
cd etc
ls
cd ansible
ls
cd hosts
nano hosts
cd ..
cd ~
ls
cd ansible-playbooks/
ls
nano inventory
ansible-playbook -i inventory/home/ansible/ansible-playbooks/playbook1.yml
pwd
ansible-playbook -i inventory/home/ansible/ansible-playbooks/playbook1.yml
ansible-playbook -i /home/ansible/ansible-playbooks/inventory/home/ansible/ansible-playbooks/playbook1.yml
p;p;;;;;;;pooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
ansible-playbook -i inventory /home/ansible/ansible-playbooks/playbook1.yml
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml
ls
nano playbook1.yml
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml
nano inventory
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml
nano playbook1.yml
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml
nano inventory
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml
nano inventory
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml
nano playbook1.yml
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml
nano inventory
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml
nano playbook1.yml
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml
ssh -i "pranavi.pem" ec2-user@ec2-3-221-155-17.compute-1.amazonaws.com
nano inventory
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml
ssh -i "pranavi.pem" ec2-user@ec2-34-226-154-141.compute-1.amazonaws.com
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml
ssh -i "pranavi.pem" ec2-user@ec2-34-226-154-141.compute-1.amazonaws.com
ssh -i "pranavi.pem" webserver@ec2-34-226-154-141.compute-1.amazonaws.com
ssh webserver@ec2-34-226-154-141.compute-1.amazonaws.com
ssh webserver@34.226.154.141
cd /
ls
cd etc
ls
cd ssh
ls
cd sshd_config
nano sshd_config
sudo nano sshd_config
cd ~
ls
cd ansible-playbooks/
ssh webserver@34.226.154.141
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml
nano inventory
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml
nano inventory
ansible webserver -m ping
ansible -i inventory webserver -m ping
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml --ask-become-pass
ls
nano playbook1.yml 
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml --ask-become-pass
ssh -i "pranavi.pem" ec2-user@ec2-3-221-155-17.compute-1.amazonaws.com
nano playbook1.yml 
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml --ask-become-pass
nano playbook1.yml 
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml --ask-become-pass
nano playbook1.yml
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml --ask-become-pass
nano playbook1.yml 
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml --ask-become-pass
nano playbook1.yml 
ansible-playbook -i /home/ansible/ansible-playbooks/inventory /home/ansible/ansible-playbooks/playbook1.yml --ask-become-pass
nano playbook1.yml 
